### PR TITLE
Remove Lixkote's contributions

### PR DESCRIPTION
**Pull request by ImSwordQueen**
He doesn't want his stuff on this project. So they should be removed.

### CODE REVIEW

**Comment by ImSwordQueen** [comment]
👍

**Comment by ImSwordQueen** [comment]
Shut up HNA

**Comment by ImSwordQueen** [comment]
Shush

**Comment by ImSwordQueen** [comment]
Nobody wants you in the server HNA. leave.

**Comment by Typical0** [comment]
@ImSwordQueen you deleted both extras and themes, don't you think they should be kept for fuck's sake

**Comment by ImSwordQueen** [comment]
You are right typical. I didn't think about that

**Comment by ImSwordQueen** [comment]
Skill issue HNA

**Comment by travy-patty** [comment]
that's crazy

**Comment by ImSwordQueen** [comment]
Dear Friend,

I'm writing this letter to apologize for my recent behavior. I know I have been distant, irritable, and unresponsive lately. I know I have let you down and hurt you with my words and actions.

I want you to know that I'm not doing this on purpose. I'm struggling with depression and it's affecting every aspect of my life. Depression makes me feel hopeless, worthless, and empty. It drains my energy and motivation. It makes me isolate myself and push away the people who care about me.

I'm not trying to make excuses for myself. I take full responsibility for my actions and I'm sorry for the pain I caused you. You are a wonderful friend and you deserve better than this. You have always been there for me, supporting me, listening to me, and cheering me up. You are one of the few people who make me happy and I don't want to lose you.

Please forgive me for being a bad friend. I'm working on getting better. I'm seeing a therapist and taking medication. I'm trying to be more positive and proactive. I'm trying to reach out more and reconnect with you and others. I know it will take time and effort, but I'm hopeful that things will improve.

I miss you and I value your friendship. I hope you can give me another chance and understand what I'm going through. I hope we can talk soon and catch up on everything. Please let me know how you are doing and what you need from me.

Thank you for being patient and compassionate with me. Thank you for being my friend.

Sincerely,
Your Name

**Comment by ImSwordQueen** [comment]
Dear Team,

I'm writing this letter to apologize for my poor performance on the rectify11 project. I know I have failed to meet your expectations and deliver quality work on time. I know I have caused delays, errors, and frustration for you and the client.

I want you to know that I'm not proud of myself. I take full responsibility for my actions and I'm sorry for the negative impact I had on the project and the team. You are all talented and hardworking professionals and you deserve better than this. You have always been supportive, collaborative, and respectful of me and my work. You are a great team and I'm lucky to be a part of it.

Please forgive me for being a bad team member. I'm working on improving myself and my skills. I'm seeking feedback, learning from my mistakes, and taking corrective actions. I'm trying to be more organized, proactive, and communicative. I know it will take time and effort, but I'm determined to do better.

I appreciate your patience and understanding with me. I hope you can give me another chance and trust me again. I hope we can work together smoothly and successfully on future projects. Please let me know how I can help you and what you need from me.

Thank you for being kind and compassionate with me. Thank you for being my team.

Sincerely,
Your Name

**Comment by ImSwordQueen** [comment]
@everyone :)

**Comment by ImSwordQueen** [comment]
Ok

**Comment by ImSwordQueen** [comment]
I did. it corrupted during sysprep

**Comment by ImSwordQueen** [comment]
ok gloom enjoyer

**Comment by ImSwordQueen** [comment]
UwU gloom gives me the buddies

**Comment by ImSwordQueen** [comment]
Brother i don't give nothing to make a good bootleg. the wallpapers are literally AI generated

**Comment by ImSwordQueen** [comment]
Brother desecting a bootleg. go outside holy shit

**Comment by ImSwordQueen** [comment]
https://twitter.com/Rectify11Ls/status/1652732289388797955 Leaving this here oops....

**Comment by ImSwordQueen** [comment]
Started at the bottom still there https://twitter.com/Rectify11Ls/status/1652732289388797955

**Comment by ImSwordQueen** [comment]
Stop defending someone that sends 18+ invites to previously minors a day prior https://twitter.com/Rectify11Ls/status/1652732289388797955

**Comment by MishaProductions** [comment]
This will be done in a separate commit.

**Comment by Lixkote** [comment]
> This will be done in a separate commit.

Honesly, you can leave my commits.

**Comment by travy-patty** [comment]
i think its too late for that ! oh crud!

**Pull request closed without merging**
